# Imports

In [11]:
%matplotlib inline

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Numpy

In [40]:
print(np.arange(4) + 10 )
#generates numbers 0-3 and adds 10 to each.

print(np.random.rand(5)) #generates random numbers

[10 11 12 13]
[0.47958562 0.16184485 0.13472338 0.92150846 0.35690655]


In [6]:
hello = 'hello'
world = 'world'
print('%s %s %d' % (hello, world, 12)) #sprintf style string formatting
print(hello.capitalize()) # just changes the 1st letter to upper
print(hello.upper()) #changes whole word to upper case

hello world 12
Hello
HELLO


- Numpy is grid of values of same type.
- The indexes are represented in tuples.
- The length of indexes/number of dimension is known as the rank of array.

An element in the array can be accessed using the index. e.g. b[2,3] gives the 3rd rows 4th column value.

- np.zeros((m,n)) - creates a m x n matrix with all the elements as 0
- np.ones((m,n)) - creates a m x n matrix with all the elements as 1.
- np.full((m,n), a) - creates a m x n matrix but fills it with a.
- np.eye(m) - creates m x m matrix that has all the diagonal element as 1.
- np.random.random((m, n)) - creates matrix of m x n where all the elements are picked from gaussian random distribution.

Slicing is possible but for that a separate copy is not created.
Its good to slice using range where the upper limit is not included because it generates the same rank array but if we use just the integer it would produce a lower rank array.

In [27]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0,1]) # This is 0th row 1st column value if this is placed in matrix form

b = a[:2,1:3] #slice and dice the matrix to fetch rows 0 & 1 and column 1 & 2
print(b)

print(b[0,0]) # this is equal to a[0,1]

b[0,0] = 77

print(b[0,0])
print(a[0,1]) # this indicates the references are to the same value and another copy was not created.

x = a[[0,2],]
print(x) #this uses the integers but produces same ranked array as the original
print('Rank of a = ', np.ndim(a), 'Shape of a = ', a.shape)
print('Rank of x = ', np.ndim(x), 'shape of x = ', x.shape,'\n') # rank has been depricated and ndim can be used now

x = a[0,]
print(x)
print('Rank of a = ', np.ndim(a), 'Shape of a = ', a.shape)
print('Rank of x = ', np.ndim(x), 'shape of x = ', x.shape,'\n')

x = a[0:1,]
print(x)
print('Rank of a = ', np.ndim(a), 'Shape of a = ', a.shape)
print('Rank of x = ', np.ndim(x), 'shape of x = ', x.shape)

#Here we have used row for example but columns can also be used.

2
[[2 3]
 [6 7]]
2
77
77
[[ 1 77  3  4]
 [ 9 10 11 12]]
Rank of a =  2 Shape of a =  (3, 4)
Rank of x =  2 shape of x =  (2, 4) 

[ 1 77  3  4]
Rank of a =  2 Shape of a =  (3, 4)
Rank of x =  1 shape of x =  (4,) 

[[ 1 77  3  4]]
Rank of a =  2 Shape of a =  (3, 4)
Rank of x =  2 shape of x =  (1, 4)


In [35]:
print(a[[0,1,2],[0,1,3]]) # in here we give the indexes of row as one list 
# and indexes of columns as another list to get the output which is same as
print(np.array([a[0,0], a[1,1], a[2,3]])) #or
print(a[[0,0], [1,1]]) # = 
print(np.array([a[0,1], a[0,1]])) #if we are not using np.array we would get list instead of array

[ 1  6 12]
[ 1  6 12]
[77 77]
[77 77]


In [43]:
a  = np.array([[2, 5, 8], [1, 8, 7], [3, 10, 4]])

bool_array = (a > 5) #this produces a matrix
print(bool_array)

print(a[bool_array]) #when the bool matrix is used it produces array of rank 1.

[[False False  True]
 [False  True  True]
 [False  True False]]
[ 8  8  7 10]


 - Numpy arrays are grid of elements of same type unlike lists.
 - np.add, np.substract, np.multiply, np.divide, np.sqrt etc are functions that operates on each element of nd arrays.
 - for matrix multiplication (vector multiplication) np.dot function is used.
 - np.sum(matrix) will give sum of all the elements in the matrix.
 - np.sum(x, axis=0) adds the elements across rows for each column. where as axis=1 adds the element across columns for each row.
 - T is used to get the transpose of a matrix.

# Pandas

In [24]:
pd.set_option("display.max_rows", 5)
pd.set_option('display.max_columns', 100) 
#this is used to display the number of rows and columns for each output
#this line of code will only return 5 results and to a max of 100 columns for each execution

reviews = pd.read_csv('../data/Kaggle/datasets/winemag-data-130k-v2.csv', index_col=0)
gaming_products = pd.read_csv("../data/Kaggle/datasets/things-on-reddit/top-things/reddits/g/gaming.csv")
gaming_products['subreddit'] = "r/gaming"
movie_products = pd.read_csv("../data/Kaggle/datasets/things-on-reddit/top-things/reddits/m/movies.csv")
movie_products['subreddit'] = "r/movies"
powerlifting_meets = pd.read_csv("../data/Kaggle/datasets/meets.csv")
powerlifting_competitors = pd.read_csv("../data/Kaggle/datasets/openpowerlifting.csv")

canadian_youtube = pd.read_csv("../data/Kaggle/datasets/CAvideos.csv")
british_youtube = pd.read_csv("../data/Kaggle/datasets/GBvideos.csv")

## Creating, Reading and writing
**Kaggle Learn Pandas 1**

In [1]:
import pandas as pd

A pandas series is collection of data and it can have a name. It also can have name for each row.
The name of the series is same as the column name in a DataFrame. (see below)

In [2]:
pd.Series([2000,2500,'4600'], index=['JanSale', 'FebSale', 'MarchSale'], name='Sarees')

JanSale      2000
FebSale      2500
MarchSale    4600
Name: Sarees, dtype: object

Pandas DataFrame is nothing but collection of multiple series of data. The dataframe can be defined as a dictionary of labeled list and the indexes can be added as the list. The labels are the names of each series(columns) where as the indexes are the names for each row.
The labels are names of individual series in a DataFrame.

In [3]:
df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]}, index=['Item 1', 'Item 2', 'Item 3'])
df

A  B
Item 1  1  4
Item 2  2  5
Item 3  3  6

A series in a dataframe can be accessed using the name e.g. df.A or df['A']

## Indexing, Selecting Assigning Reference

## Summary Functions and Maps

## Pandas Grouping and Sorting

### groupby

In [66]:
reviews.groupby('country').country.count()

country
Argentina    3800
Armenia         2
             ... 
Ukraine        14
Uruguay       109
Name: country, Length: 43, dtype: int64

In [78]:
reviews.groupby('country').price.mean()

country
Argentina    24.510117
Armenia      14.500000
               ...    
Ukraine       9.214286
Uruguay      26.403670
Name: price, Length: 43, dtype: float64

In [67]:
reviews.groupby('winery').apply(lambda df: len(df))

winery
1+1=3        6
10 Knots     4
            ..
àMaurice    40
Štoka        3
Length: 16757, dtype: int64

In [68]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])
#here loc wont work as the loc takes specific index name and index for each group is not 0

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...                        
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [81]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[int(df.points.idxmax())])
#the argmax/idxmax function returns the index from original dataset and if we send it to iloc which is local/individual dataset indexer
#it will not be able to find all the indexes for all the groups. Therefore we need to use loc to handle the indexes referenced at
# main dataset.
#argmax/idxmax returns the main dataset index because the local indexes are not real but virtual.

country  \
country   province                      
Argentina Mendoza Province  Argentina   
          Other             Argentina   
...                               ...   
Uruguay   San Jose            Uruguay   
          Uruguay             Uruguay   

                                                                  description  \
country   province                                                              
Argentina Mendoza Province  If the color doesn't tell the full story, the ...   
          Other             Take note, this could be the best wine Colomé ...   
...                                                                       ...   
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...   
          Uruguay           Cherry and berry aromas are ripe, healthy and ...   

                                          designation  points  price  \
country   province                                                     
Argentina Mendoza Province           Nicasia Vineyard      97  120.0   
          Other                               Reserva      95   90.0   
...                                               ...     ...    ...   
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0   
          Uruguay           Blend 002 Limited Edition      91   22.0   

                                    province region_1 region_2  \
country   province                                               
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN   
          Other                        Other    Salta      NaN   
...                                      ...      ...      ...   
Uruguay   San Jose                  San Jose      NaN      NaN   
          Uruguay                    Uruguay      NaN      NaN   

                                  taster_name taster_twitter_handle  \
country   province                                                    
Argentina Mendoza Province  Michael Schachner           @wineschach   
          Other             Michael Schachner           @wineschach   
...                                       ...                   ...   
Uruguay   San Jose          Michael Schachner           @wineschach   
          Uruguay           Michael Schachner           @wineschach   

                                                                        title  \
country   province                                                              
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...   
          Other                            Colomé 2010 Reserva Malbec (Salta)   
...                                                                       ...   
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...   
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...   

                                          variety                winery  
country   province                                                       
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata  
          Other                            Malbec                Colomé  
...                                           ...                   ...  
Uruguay   San Jose                      Red Blend        Castillo Viejo  
          Uruguay           Tannat-Cabernet Franc               Narbona  

[425 rows x 13 columns]

In [70]:
def median(df):
    sum(df)/len(df)
reviews.groupby('country').price.agg([len, min, max])

len   min    max
country                       
Argentina  3800.0   4.0  230.0
Armenia       2.0  14.0   15.0
...           ...   ...    ...
Ukraine      14.0   6.0   13.0
Uruguay     109.0  10.0  130.0

[43 rows x 3 columns]

In [71]:
reviews.groupby('country').count()
#the above piece of code gives a total true data of each column for each country i.e. ignoring NaN/Null etc.

description  designation  points  price  province  region_1  \
country                                                                  
Argentina         3800         2902    3800   3756      3800      3747   
Armenia              2            2       2      2         2         0   
...                ...          ...     ...    ...       ...       ...   
Ukraine             14           12      14     14        14         0   
Uruguay            109           95     109    109       109         0   

           region_2  taster_name  taster_twitter_handle  title  variety  \
country                                                                   
Argentina         0         3797                   3797   3800     3800   
Armenia           0            2                      2      2        2   
...             ...          ...                    ...    ...      ...   
Ukraine           0           14                     12     14       14   
Uruguay           0          109                    109    109      109   

           winery  
country            
Argentina    3800  
Armenia         2  
...           ...  
Ukraine        14  
Uruguay       109  

[43 rows x 12 columns]

### MultiIndex

In [94]:
group_mi = reviews.groupby(['country', 'province']).price.agg([len, min, max])
group_mi = group_mi.reset_index()
group_mi

country          province     len   min    max
0    Argentina  Mendoza Province  3264.0   4.0  230.0
1    Argentina             Other   536.0   7.0  150.0
..         ...               ...     ...   ...    ...
423    Uruguay          San Jose     3.0  20.0   50.0
424    Uruguay           Uruguay    24.0  12.0   50.0

[425 rows x 5 columns]

### Sorting

In [97]:
group_mi.sort_values(by=['len', 'max'], ascending=False)

country         province      len  min     max
392            US       California  36247.0  4.0  2013.0
415            US       Washington   8639.0  6.0   240.0
..            ...              ...      ...  ...     ...
335  South Africa    Ceres Plateau      1.0  NaN     NaN
357  South Africa  Piekenierskloof      1.0  NaN     NaN

[425 rows x 5 columns]

## Data Types and Missing Data

### Data Types

Dataframe, series, array, lists, tuples etc are data structures to hold data of some type. These are basically int, float string and boolean.

In a dataframe/series it is provided as a property as **'dtype'/'dtypes'**. 
'type()' function will give datatype of the object passed to it.

df.col.astype('float64') -> this converts the datatype.
Usually for dataframes any thing stored as string is object type rather than string or character type.

Pandas also support categorical and timeseries data types as well.

### Missing Data

In [122]:
print(reviews.isnull())
print(reviews.isnull().sum()) # for each column how many nulls are there. By default axis is 0.
print(reviews.isnull().sum(axis=1)) # For each row how many nulls are there

        country  description  designation  points  price  province  region_1  \
0         False        False        False   False   True     False     False   
1         False        False        False   False  False     False      True   
...         ...          ...          ...     ...    ...       ...       ...   
129969    False        False         True   False  False     False     False   
129970    False        False        False   False  False     False     False   

        region_2  taster_name  taster_twitter_handle  title  variety  winery  
0           True        False                  False  False    False   False  
1           True        False                  False  False    False   False  
...          ...          ...                    ...    ...      ...     ...  
129969      True        False                  False  False    False   False  
129970      True        False                  False  False    False   False  

[129971 rows x 13 columns]
country        63

In [107]:
print(reviews.price.isnull().sum(), reviews.price.notnull().sum(), len(reviews))

8996 120975 129971


In [109]:
reviews.price.fillna(0.1) # whereever the value is NaN it will be replaced with 0.1

0          0.1
1         15.0
          ... 
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

In [120]:
reviews.fillna(method='ffill')

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
...          ...                                                ...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
...                               ...     ...    ...                ...   
129969                          Kritt      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

       region_1      region_2    taster_name taster_twitter_handle  \
0          Etna           NaN  Kerin O’Keefe          @kerinokeefe   
1          Etna           NaN     Roger Voss            @vossroger   
...         ...           ...            ...                   ...   
129969   Alsace  Oregon Other     Roger Voss            @vossroger   
129970   Alsace  Oregon Other     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 13 columns]

## Renaming and Combining Data

### Renaming

In [16]:
#e.g.
print(reviews.columns)
reviews.rename({'region_1':'region', 'points':'score','region_2':'locale'},axis='columns')

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')


country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
...          ...                                                ...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                          designation  score  price           province  \
0                        Vulkà Bianco     87    NaN  Sicily & Sardinia   
1                            Avidagos     87   15.0              Douro   
...                               ...    ...    ...                ...   
129969                            NaN     90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline     90   21.0             Alsace   

        region locale    taster_name taster_twitter_handle  \
0         Etna    NaN  Kerin O’Keefe          @kerinokeefe   
1          NaN    NaN     Roger Voss            @vossroger   
...        ...    ...            ...                   ...   
129969  Alsace    NaN     Roger Voss            @vossroger   
129970  Alsace    NaN     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 13 columns]

In [19]:
#e.g.
reviews.rename_axis('wines', axis='rows').rename_axis('fields', axis='columns')

fields   country                                        description  \
wines                                                                 
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
...          ...                                                ...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

fields                    designation  points  price           province  \
wines                                                                     
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
...                               ...     ...    ...                ...   
129969                            NaN      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

fields region_1 region_2    taster_name taster_twitter_handle  \
wines                                                           
0          Etna      NaN  Kerin O’Keefe          @kerinokeefe   
1           NaN      NaN     Roger Voss            @vossroger   
...         ...      ...            ...                   ...   
129969   Alsace      NaN     Roger Voss            @vossroger   
129970   Alsace      NaN     Roger Voss            @vossroger   

fields                                              title         variety  \
wines                                                                       
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

fields                winery  
wines                         
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 13 columns]

In [18]:
#e.g.
#data.set_index(["First Name", "Gender"], inplace = True, append = True, drop = False) 
#first Name and Gender are the columns which are converted to index names
#Its usually going to be a column with unique data for each row.

### Combining

In [25]:
pd.concat([canadian_youtube, british_youtube])

video_id trending_date  \
0      n1WpP7iowLc      17.14.11   
1      0dBIkQ4Mz1M      17.14.11   
...            ...           ...   
38914  -DRsfNObKIQ      18.14.06   
38915  4YFo4bdMO8Q      18.14.06   

                                                   title  \
0             Eminem - Walk On Water (Audio) ft. Beyoncé   
1                          PLUSH - Bad Unboxing Fan Mail   
...                                                  ...   
38914  Eleni Foureira - Fuego - Cyprus - LIVE - First...   
38915  KYLE - Ikuyo feat.  2 Chainz & Sophia Black [A...   

                 channel_title  category_id              publish_time  \
0                   EminemVEVO           10  2017-11-10T17:00:03.000Z   
1                    iDubbbzTV           23  2017-11-13T17:00:00.000Z   
...                        ...          ...                       ...   
38914  Eurovision Song Contest           24  2018-05-08T20:32:32.000Z   
38915           SuperDuperKyle           10  2018-05-11T04:06:35.000Z   

                                                    tags     views   likes  \
0      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579  787425   
1      plush|"bad unboxing"|"unboxing"|"fan mail"|"id...   1014651  127794   
...                                                  ...       ...     ...   
38914  Eurovision Song Contest|"2018"|"Lisbon"|"Cypru...  14317515  151870   
38915  Kyle|"SuperDuperKyle"|"Ikuyo"|"2 Chainz"|"Soph...    607552   18271   

       dislikes  comment_count  \
0         43420         125882   
1          1688          13030   
...         ...            ...   
38914     45875          26766   
38915       274           1423   

                                       thumbnail_link  comments_disabled  \
0      https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg              False   
1      https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg              False   
...                                               ...                ...   
38914  https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg              False   
38915  https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg              False   

       ratings_disabled  video_error_or_removed  \
0                 False                   False   
1                 False                   False   
...                 ...                     ...   
38914             False                   False   
38915             False                   False   

                                             description  
0      Eminem's new track Walk on Water ft. Beyoncé i...  
1      STill got a lot of packages. Probably will las...  
...                                                  ...  
38914  Eleni Foureira represented Cyprus at the first...  
38915  Debut album 'Light of Mine' out now: http://ky...  

[79797 rows x 16 columns]

In [26]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK') #by default this is outer join and we can make it inner join using how='inner'

video_id_CAN  \
title                                              trending_date                
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI   
...                                                                       ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Wt9Gkpmbt44   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Az72jrKbANA   

                                                                                channel_title_CAN  \
title                                              trending_date                                    
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                            Markiplier   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        AlexRamiGaming   
...                                                                                           ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                         TheBigJackpot   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Right Side Broadcasting Network   

                                                                  category_id_CAN  \
title                                              trending_date                    
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20   
...                                                                           ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    24   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    25   

                                                                          publish_time_CAN  \
title                                              trending_date                             
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z   
...                                                                                    ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       2018-05-07T06:58:59.000Z   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       2018-04-03T23:12:37.000Z   

                                                                                                           tags_CAN  \
title                                              trending_date                                                      
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...   
...                                                                                                             ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Slot Machine|"win"|"Gambling"|"Big Win"|"raja"...   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       YouTube shooter|"YouTube active shooter"|"acti...   

                                                                  views_CAN  \
title                                              trending_date              
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930   
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838   
...                                                                     ...   
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           28973   
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04          103513   

                                                                  likes_CAN  \
title                                              trending_date   

In [37]:
canadian_youtube.set_index('video_id').join(british_youtube.set_index('video_id'), lsuffix='_can', rsuffix='_uk', how='inner', on='video_id')

trending_date_can  \
video_id                        
n1WpP7iowLc          17.14.11   
n1WpP7iowLc          17.14.11   
...                       ...   
-QPdRfqTnt4          18.14.06   
r63VBOagGAo          18.14.06   

                                                     title_can  \
video_id                                                         
n1WpP7iowLc         Eminem - Walk On Water (Audio) ft. Beyoncé   
n1WpP7iowLc         Eminem - Walk On Water (Audio) ft. Beyoncé   
...                                                        ...   
-QPdRfqTnt4                      Dumbo Official Teaser Trailer   
r63VBOagGAo  Shawn Mendes x Portugal (FPF Official World Cu...   

                 channel_title_can  category_id_can          publish_time_can  \
video_id                                                                        
n1WpP7iowLc             EminemVEVO               10  2017-11-10T17:00:03.000Z   
n1WpP7iowLc             EminemVEVO               10  2017-11-10T17:00:03.000Z   
...                            ...              ...                       ...   
-QPdRfqTnt4  Disney Movie Trailers                1  2018-06-13T07:00:00.000Z   
r63VBOagGAo       FPFutebolOficial               17  2018-06-13T13:11:56.000Z   

                                                      tags_can  views_can  \
video_id                                                                    
n1WpP7iowLc  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...   17158579   
n1WpP7iowLc  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...   17158579   
...                                                        ...        ...   
-QPdRfqTnt4  Disney|"Walt Disney Studios"|"Dumbo"|"Flying E...    4427381   
r63VBOagGAo  Canal|"Oficial"|"da"|"Federação"|"Portuguesa"|...     653114   

             likes_can  dislikes_can  comment_count_can  \
video_id                                                  
n1WpP7iowLc     787425         43420             125882   
n1WpP7iowLc     787425         43420             125882   
...                ...           ...                ...   
-QPdRfqTnt4      96391          5508              12726   
r63VBOagGAo      65635           547               3819   

                                         thumbnail_link_can  \
video_id                                                      
n1WpP7iowLc  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg   
n1WpP7iowLc  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg   
...                                                     ...   
-QPdRfqTnt4  https://i.ytimg.com/vi/-QPdRfqTnt4/default.jpg   
r63VBOagGAo  https://i.ytimg.com/vi/r63VBOagGAo/default.jpg   

             comments_disabled_can  ratings_disabled_can  \
video_id                                                   
n1WpP7iowLc                  False                 False   
n1WpP7iowLc                  False                 False   
...                            ...                   ...   
-QPdRfqTnt4                  False                 False   
r63VBOagGAo                  False                 False   

             video_error_or_removed_can  \
video_id                                  
n1WpP7iowLc                       False   
n1WpP7iowLc                       False   
...                                 ...   
-QPdRfqTnt4                       False   
r63VBOagGAo                       False   

                                               description_can  \
video_id                                                         
n1WpP7iowLc  Eminem's new track Walk on Water ft. Beyoncé i...   
n1WpP7iowLc  Eminem's new track Walk on Water ft. Beyoncé i...   
...                                                        ...   
-QPdRfqTnt4  Watch the teaser trailer for Tim Burton’s all-...   
r63VBOagGAo  Portugal's Football Team Official SongLyrics: ...   

            trending_date_uk  \
video_id                       
n1WpP7iowLc         17.14.11   
n1WpP7iowLc         17.15.11   
...                      ...   
-QPdRfq

In [33]:
#code for merge
pd.merge(canadian_youtube, british_youtube, how='inner', on='video_id')

video_id trending_date_x  \
0      n1WpP7iowLc        17.14.11   
1      n1WpP7iowLc        17.14.11   
...            ...             ...   
47340  -QPdRfqTnt4        18.14.06   
47341  r63VBOagGAo        18.14.06   

                                                 title_x  \
0             Eminem - Walk On Water (Audio) ft. Beyoncé   
1             Eminem - Walk On Water (Audio) ft. Beyoncé   
...                                                  ...   
47340                      Dumbo Official Teaser Trailer   
47341  Shawn Mendes x Portugal (FPF Official World Cu...   

             channel_title_x  category_id_x            publish_time_x  \
0                 EminemVEVO             10  2017-11-10T17:00:03.000Z   
1                 EminemVEVO             10  2017-11-10T17:00:03.000Z   
...                      ...            ...                       ...   
47340  Disney Movie Trailers              1  2018-06-13T07:00:00.000Z   
47341       FPFutebolOficial             17  2018-06-13T13:11:56.000Z   

                                                  tags_x   views_x  likes_x  \
0      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   787425   
1      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   787425   
...                                                  ...       ...      ...   
47340  Disney|"Walt Disney Studios"|"Dumbo"|"Flying E...   4427381    96391   
47341  Canal|"Oficial"|"da"|"Federação"|"Portuguesa"|...    653114    65635   

       dislikes_x  comment_count_x  \
0           43420           125882   
1           43420           125882   
...           ...              ...   
47340        5508            12726   
47341         547             3819   

                                     thumbnail_link_x  comments_disabled_x  \
0      https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg                False   
1      https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg                False   
...                                               ...                  ...   
47340  https://i.ytimg.com/vi/-QPdRfqTnt4/default.jpg                False   
47341  https://i.ytimg.com/vi/r63VBOagGAo/default.jpg                False   

       ratings_disabled_x  video_error_or_removed_x  \
0                   False                     False   
1                   False                     False   
...                   ...                       ...   
47340               False                     False   
47341               False                     False   

                                           description_x trending_date_y  \
0      Eminem's new track Walk on Water ft. Beyoncé i...        17.14.11   
1      Eminem's new track Walk on Water ft. Beyoncé i...        17.15.11   
...                                                  ...             ...   
47340  Watch the teaser trailer for Tim Burton’s all-...        18.14.06   
47341  Portugal's Football Team Official SongLyrics: ...        18.14.06   

                                                 title_y  \
0             Eminem - Walk On Water (Audio) ft. Beyoncé   
1             Eminem - Walk On Water (Audio) ft. Beyoncé   
...                                                  ...   
47340                      Dumbo Official Teaser Trailer   
47341  Shawn Mendes x Portugal (FPF Official World Cu...   

             channel_title_y  category_id_y            publish_time_y  \
0                 EminemVEVO             10  2017-11-10T17:00:03.000Z   
1                 EminemVEVO             10  2017-11-10T17:00:03.000Z   
...                      ...            ...                       ...   
47340  Disney Movie Trailers              1  2018-06-13T07:00:00.000Z   
47341       FPFutebolOficial             17  2018-06-13T13:11:56.000Z   

                                                  tags_y   views_y  likes_y  \
0      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   787420   
1      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  2053

In [42]:
#code for append
canadian_youtube.set_index('video_id').append(british_youtube.set_index('video_id'))
#Now we can see that the video_id is there as index, but if we use ignore_index=true we can remove the index from output

trending_date                                              title  \
video_id                                                                       
n1WpP7iowLc      17.14.11         Eminem - Walk On Water (Audio) ft. Beyoncé   
0dBIkQ4Mz1M      17.14.11                      PLUSH - Bad Unboxing Fan Mail   
...                   ...                                                ...   
-DRsfNObKIQ      18.14.06  Eleni Foureira - Fuego - Cyprus - LIVE - First...   
4YFo4bdMO8Q      18.14.06  KYLE - Ikuyo feat.  2 Chainz & Sophia Black [A...   

                       channel_title  category_id              publish_time  \
video_id                                                                      
n1WpP7iowLc               EminemVEVO           10  2017-11-10T17:00:03.000Z   
0dBIkQ4Mz1M                iDubbbzTV           23  2017-11-13T17:00:00.000Z   
...                              ...          ...                       ...   
-DRsfNObKIQ  Eurovision Song Contest           24  2018-05-08T20:32:32.000Z   
4YFo4bdMO8Q           SuperDuperKyle           10  2018-05-11T04:06:35.000Z   

                                                          tags     views  \
video_id                                                                   
n1WpP7iowLc  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   
0dBIkQ4Mz1M  plush|"bad unboxing"|"unboxing"|"fan mail"|"id...   1014651   
...                                                        ...       ...   
-DRsfNObKIQ  Eurovision Song Contest|"2018"|"Lisbon"|"Cypru...  14317515   
4YFo4bdMO8Q  Kyle|"SuperDuperKyle"|"Ikuyo"|"2 Chainz"|"Soph...    607552   

              likes  dislikes  comment_count  \
video_id                                       
n1WpP7iowLc  787425     43420         125882   
0dBIkQ4Mz1M  127794      1688          13030   
...             ...       ...            ...   
-DRsfNObKIQ  151870     45875          26766   
4YFo4bdMO8Q   18271       274           1423   

                                             thumbnail_link  \
video_id                                                      
n1WpP7iowLc  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg   
0dBIkQ4Mz1M  https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg   
...                                                     ...   
-DRsfNObKIQ  https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg   
4YFo4bdMO8Q  https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg   

             comments_disabled  ratings_disabled  video_error_or_removed  \
video_id                                                                   
n1WpP7iowLc              False             False                   False   
0dBIkQ4Mz1M              False             False                   False   
...                        ...               ...                     ...   
-DRsfNObKIQ              False             False                   False   
4YFo4bdMO8Q              False             False                   False   

                                                   description  
video_id                                                        
n1WpP7iowLc  Eminem's new track Walk on Water ft. Beyoncé i...  
0dBIkQ4Mz1M  STill got a lot of packages. Probably will las...  
...                                                        ...  
-DRsfNObKIQ  Eleni Foureira represented Cyprus at the first...  
4YFo4bdMO8Q  Debut album 'Light of Mine' out now: http://ky...  

[79797 rows x 15 columns]

## Method Chaining

# Maptplotlib

# Kaggle dataset collection

 ***Download Data from kaggle unzip it and delete the zip file***

In [18]:
!kaggle datasets download jpmiller/publicassistance -f sub-est2016_all.csv -p ../data/ --unzip

sub-est2016_all.csv.zip: Skipping, found more recently modified local copy (use --force to force download)


In [19]:
!unzip ../data/sub-est2016_all.csv.zip -d ../data

Archive:  ../data/sub-est2016_all.csv.zip
  inflating: ../data/sub-est2016_all.csv  


In [ ]:
!rm ../data/sub-est2016_all.csv.zip

In [1]:
!kaggle datasets download -d open-powerlifting/powerlifting-database --unzip -p ../data/Kaggle/datasets/


  0%|          | 0.00/8.85M [00:00<?, ?B/s]
 11%|#1        | 1.00M/8.85M [00:00<00:01, 7.28MB/s]
 23%|##2       | 2.00M/8.85M [00:00<00:01, 4.89MB/s]
 57%|#####6    | 5.00M/8.85M [00:00<00:00, 5.75MB/s]
 90%|######### | 8.00M/8.85M [00:00<00:00, 7.37MB/s]
100%|##########| 8.85M/8.85M [00:00<00:00, 9.33MB/s]


In [7]:
!kaggle datasets download -d residentmario/things-on-reddit --unzip -p ../data/Kaggle/datasets/


  0%|          | 0.00/7.27M [00:00<?, ?B/s]
 28%|##7       | 2.00M/7.27M [00:00<00:00, 18.1MB/s]
 69%|######8   | 5.00M/7.27M [00:00<00:00, 20.0MB/s]
100%|##########| 7.27M/7.27M [00:00<00:00, 25.3MB/s]


In [10]:
!unzip ../data/Kaggle/datasets/top-things.zip -d ../data/Kaggle/datasets/things-on-reddit

Archive:  ../data/Kaggle/datasets/top-things.zip
   creating: ../data/Kaggle/datasets/things-on-reddit/top-things/
   creating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/
   creating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/100DaysofKeto.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/100yearsago.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/1022.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/10cloverfieldlane.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/1200isjerky.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/1200isplenty.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/1200isplentyketo.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/1/13

  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/orangecounty.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/orangeisthenewblack.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/orangetheory.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/orchids.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/OreGairuSNAFU.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/oregon.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/organization.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/origami.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/originalxbox.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/o/orioles.csv  
  inflating: ../data/Kaggle/datasets/things-on-reddit/top-things/reddits/

In [21]:
!kaggle datasets download -d datasnaek/youtube-new --unzip -p ../data/Kaggle/datasets/


  0%|          | 0.00/113M [00:00<?, ?B/s]
  2%|1         | 2.00M/113M [00:00<00:07, 16.0MB/s]
  4%|4         | 5.00M/113M [00:00<00:07, 15.1MB/s]
  8%|7         | 9.00M/113M [00:00<00:06, 18.2MB/s]
 11%|#         | 12.0M/113M [00:00<00:06, 17.4MB/s]
 14%|#4        | 16.0M/113M [00:00<00:04, 20.4MB/s]
 17%|#6        | 19.0M/113M [00:01<00:05, 17.2MB/s]
 20%|##        | 23.0M/113M [00:01<00:04, 20.3MB/s]
 23%|##2       | 26.0M/113M [00:01<00:05, 16.1MB/s]
 26%|##6       | 30.0M/113M [00:01<00:04, 19.2MB/s]
 29%|##9       | 33.0M/113M [00:01<00:04, 17.7MB/s]
 33%|###2      | 37.0M/113M [00:01<00:03, 20.8MB/s]
 36%|###6      | 41.0M/113M [00:02<00:03, 20.5MB/s]
 40%|###9      | 45.0M/113M [00:02<00:03, 23.4MB/s]
 42%|####2     | 48.0M/113M [00:02<00:02, 23.3MB/s]
 45%|####4     | 51.0M/113M [00:02<00:02, 22.6MB/s]
 48%|####8     | 55.0M/113M [00:02<00:02, 25.2MB/s]
 51%|#####1    | 58.0M/113M [00:02<00:02, 21.8MB/s]
 55%|#####4    | 62.0M/113M [00:03<00:02, 20.8MB/s]
 58%|#####8    | 66.